sudo: false
install: git clone --depth 1 https://github.com/sstephenson/bats.git
script: PATH="./bats/bin:$PATH" test/run
language: c
env:
  - PHPENV_NATIVE_EXT=
  - PHPENV_NATIVE_EXT=1
branches:
  only:
    - master
notifications:
  email:
    on_success: never
