#!/usr/bin/env bash
#
# Summary: Display the full path to an executable
#
# Usage: phpenv which <command>
#
# Displays the full path to the executable that phpenv will invoke when
# you run the given command.

set -e
[ -n "$PHPENV_DEBUG" ] && set -x

# Provide phpenv completions
if [ "$1" = "--complete" ]; then
  exec phpenv-shims --short
fi

remove_from_path() {
  local path_to_remove="$1"
  local path_before
  local result=":${PATH//\~/$HOME}:"
  while [ "$path_before" != "$result" ]; do
    path_before="$result"
    result="${result//:$path_to_remove:/:}"
  done
  result="${result%:}"
  echo "${result#:}"
}

PHPENV_COMMAND="$1"

if [ -z "$PHPENV_COMMAND" ]; then
  phpenv-help --usage which >&2
  exit 1
fi

PHPENV_VERSION="${PHPENV_VERSION:-$(phpenv-version-name)}"

if [ "$PHPENV_VERSION" = "system" ]; then
  PATH="$(remove_from_path "${PHPENV_ROOT}/shims")"
  PHPENV_COMMAND_PATH="$(command -v "$PHPENV_COMMAND" || true)"
else
  PHPENV_COMMAND_PATH="${PHPENV_ROOT}/versions/${PHPENV_VERSION}/bin/${PHPENV_COMMAND}"
  if ! [ -x "$PHPENV_COMMAND_PATH" ]; then
    PHPENV_COMMAND_PATH="${PHPENV_ROOT}/versions/${PHPENV_VERSION}/sbin/${PHPENV_COMMAND}"
  fi
fi

OLDIFS="$IFS"
IFS=$'\n' scripts=(`phpenv-hooks which`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -x "$PHPENV_COMMAND_PATH" ]; then
  echo "$PHPENV_COMMAND_PATH"
elif [ "$PHPENV_VERSION" != "system" ] && [ ! -d "${PHPENV_ROOT}/versions/${PHPENV_VERSION}" ]; then
  echo "phpenv: version \`$PHPENV_VERSION' is not installed (set by $(phpenv-version-origin))" >&2
  exit 1
else
  echo "phpenv: $PHPENV_COMMAND: command not found" >&2

  versions="$(phpenv-whence "$PHPENV_COMMAND" || true)"
  if [ -n "$versions" ]; then
    { echo
      echo "The \`$1' command exists in these PHP versions:"
      echo "$versions" | sed 's/^/  /g'
      echo
    } >&2
  fi

  exit 127
fi
