#!/usr/bin/env bash
set -e
[ -n "$PHPENV_DEBUG" ] && set -x

# Provide phpenv completions
if [ "$1" = "--complete" ]; then
  echo system --unset
  exec phpenv-versions --bare
fi

PHPENV_VERSION="$1"
PHPENV_VERSION_FILE="${PHPENV_ROOT}/version"

if [ "$1" == "--unset" ]; then
  rm -f "$PHPENV_VERSION_FILE"
  PHPENV_VERSION=""
fi

if [ -n "$PHPENV_VERSION" ]; then
  phpenv-version-file-write "$PHPENV_VERSION_FILE" "$PHPENV_VERSION"
else
  PHPENV_VERSION=$(phpenv-version-file-read "$PHPENV_VERSION_FILE") ||
  PHPENV_VERSION=$(phpenv-version-file-read "${PHPENV_ROOT}/global") ||
  PHPENV_VERSION=$(phpenv-version-file-read "${PHPENV_ROOT}/default") ||
  PHPENV_VERSION=system
fi

echo ${PHPENV_VERSION}

# Link Apache apxs lib
[[ ! -d "${PHPENV_ROOT}/lib" ]] && mkdir "${PHPENV_ROOT}/lib"
[[ "${PHPENV_VERSION}" == "system" ]] &&
ln -fs "`/usr/sbin/apxs -q LIBEXECDIR`/libphp5.so" "${PHPENV_ROOT}/lib/libphp5.so" ||
ln -fs "${PHPENV_ROOT}/versions/${PHPENV_VERSION}/libexec/libphp5.so" "${PHPENV_ROOT}/lib/libphp5.so"
