#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export PHPENV_DEBUG=1
  shift
fi

if [ -n "$PHPENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "phpenv: $*"
    fi
  } >&2
  exit 1
}

if enable -f "${BASH_SOURCE%/*}"/../libexec/phpenv-realpath.dylib realpath 2>/dev/null; then
  abs_dirname() {
    local path
    path="$(realpath "$1")"
    echo "${path%/*}"
  }
else
  [ -z "$PHPENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"

  READLINK=$(type -p greadlink readlink | head -1)
  [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

  resolve_link() {
    $READLINK "$1"
  }

  abs_dirname() {
    local cwd="$PWD"
    local path="$1"

    while [ -n "$path" ]; do
      cd "${path%/*}"
      local name="${path##*/}"
      path="$(resolve_link "$name" || true)"
    done

    pwd
    cd "$cwd"
  }
fi

if [ -z "${PHPENV_ROOT}" ]; then
  PHPENV_ROOT="${HOME}/.phpenv"
else
  PHPENV_ROOT="${PHPENV_ROOT%/}"
fi
export PHPENV_ROOT

if [ -z "${PHPENV_DIR}" ]; then
  PHPENV_DIR="$PWD"
else
  [[ $PHPENV_DIR == /* ]] || PHPENV_DIR="$PWD/$PHPENV_DIR"
  cd "$PHPENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$PHPENV_DIR'"
  PHPENV_DIR="$PWD"
  cd "$OLDPWD"
fi
export PHPENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${PHPENV_ROOT}/plugins/"*/bin; do
  PATH="${plugin_bin}:${PATH}"
done
export PATH="${bin_path}:${PATH}"

PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:${PHPENV_ROOT}/phpenv.d"
if [ "${bin_path%/*}" != "$PHPENV_ROOT" ]; then
  # Add phpenv's own `phpenv.d` unless phpenv was cloned to PHPENV_ROOT
  PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:${bin_path%/*}/phpenv.d"
fi
PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:/usr/local/etc/phpenv.d:/etc/phpenv.d:/usr/lib/phpenv/hooks"
for plugin_hook in "${PHPENV_ROOT}/plugins/"*/etc/phpenv.d; do
  PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:${plugin_hook}"
done
PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH#:}"
export PHPENV_HOOK_PATH

shopt -u nullglob


command="$1"
case "$command" in
"" )
  { phpenv---version
    phpenv-help
  } | abort
  ;;
-v | --version )
  exec phpenv---version
  ;;
-h | --help )
  exec phpenv-help
  ;;
* )
  command_path="$(command -v "phpenv-$command" || true)"
  if [ -z "$command_path" ]; then
    if [ "$command" == "shell" ]; then
      abort "shell integration not enabled. Run \`phpenv init' for instructions."
    else
      abort "no such command \`$command'"
    fi
  fi

  shift 1
  if [ "$1" = --help ]; then
    if [[ "$command" == "sh-"* ]]; then
      echo "phpenv help \"$command\""
    else
      exec phpenv-help "$command"
    fi
  else
    exec "$command_path" "$@"
  fi
  ;;
esac
