#!/usr/bin/env bash
set -e
[ -n "$PHPENV_DEBUG" ] && set -x

# Provide phpenv completions
if [ "$1" = "--complete" ]; then
  exec phpenv shims --short
fi

PHPENV_COMMAND="$1"
if [ -z "$PHPENV_COMMAND" ]; then
  echo "usage: phpenv exec COMMAND [arg1 arg2...]" >&2
  exit 1
fi

PHPENV_COMMAND_PATH="$(phpenv-which "$PHPENV_COMMAND")"
PHPENV_BIN_PATH="${PHPENV_COMMAND_PATH%/*}"

for script in $(phpenv-hooks exec); do
  source "$script"
done

shift 1
export PATH="${PHPENV_BIN_PATH}:${PATH}"
exec -a "$PHPENV_COMMAND" "$PHPENV_COMMAND_PATH" "$@"
