#!/usr/bin/env bash
# Usage: phpenv completions <command> [<args>...]

set -e
[ -n "$PHPENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  phpenv-help --usage completions >&2
  exit 1
fi

# Provide phpenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec phpenv-commands
fi

COMMAND_PATH="$(type -P "phpenv-$COMMAND" "phpenv-sh-$COMMAND" | head -n1)"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide phpenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
