#!/usr/bin/env bash
# Summary: List hook scripts for a given phpenv command
# Usage: phpenv hooks <command>

set -e
[ -n "$PHPENV_DEBUG" ] && set -x

# Provide phpenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo version-name
  echo version-origin
  echo which
  exit
fi

PHPENV_COMMAND="$1"
if [ -z "$PHPENV_COMMAND" ]; then
  phpenv-help --usage hooks >&2
  exit 1
fi

#PHPENV_COMMAND_HOOK="$2"
#if [ -z "$PHPENV_COMMAND_HOOK" ]; then
#  PHPENV_COMMAND_HOOK="*"
#fi

if ! enable -f "${BASH_SOURCE%/*}"/phpenv-realpath.dylib realpath 2>/dev/null; then
  if [ -n "$PHPENV_NATIVE_EXT" ]; then
    echo "phpenv: failed to load \`realpath' builtin" >&2
    exit 1
  fi
READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "phpenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

realpath() {
  local cwd="$PWD"
  local path="$1"
  local name

  while [ -n "$path" ]; do
    name="${path##*/}"
    [ "$name" = "$path" ] || cd "${path%/*}"
    path="$(resolve_link "$name" || true)"
  done

  echo "${PWD}/$name"
  cd "$cwd"
}
fi

IFS=: hook_paths=($PHPENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$PHPENV_COMMAND"/*.bash; do
    realpath "$script"
  done
done
#
#for path in ${PHPENV_HOOK_PATH//:/$'\n'}; do
#  files="${path}/${PHPENV_COMMAND}/${PHPENV_COMMAND_HOOK}.bash"
#  for script in $files; do
#    if [ "$PHPENV_COMMAND_HOOK" != "*" ] && [ -x $script ]; then
#      exec "$script"
#    elif [ -f $script ]; then
#      echo $(realpath $script)
#    fi
#  done
#done
shopt -u nullglob
