#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific PHP version
#
# Usage: phpenv local <version>
#        phpenv local --unset
#
# Sets the local application-specific PHP version by writing the
# version name to a file named `.php-version'.
#
# When you run a PHP command, phpenv will look for a `.php-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, phpenv will use the global PHP version
# specified with `phpenv global'. A version specified with the
# `PHPENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a PHP version known to phpenv.
# The special version string `system' will use your default system PHP.
# Run `phpenv versions' for a list of available PHP versions.

set -e
[ -n "$PHPENV_DEBUG" ] && set -x

# Provide phpenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec phpenv-versions --bare
fi

PHPENV_VERSION="$1"

if [ "$PHPENV_VERSION" = "--unset" ]; then
  rm -f .php-version
elif [ -n "$PHPENV_VERSION" ]; then
  phpenv-version-file-write .php-version "$PHPENV_VERSION"
else
  if version_file="$(phpenv-version-file "$PWD")"; then
    phpenv-version-file-read "$version_file"
  else
    echo "phpenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
