#!/usr/bin/env bash
set -e
[ -n "$PHPENV_DEBUG" ] && set -x

# Provide phpenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec phpenv-versions --bare
fi

PHPENV_VERSION="$1"
PHPENV_VERSION_FILE=".phpenv-version"

if [ "$PHPENV_VERSION" = "--unset" ]; then
  rm -f "$PHPENV_VERSION_FILE"
elif [ -n "$PHPENV_VERSION" ]; then
  phpenv-version-file-write "$PHPENV_VERSION_FILE" "$PHPENV_VERSION"
else
  phpenv-version-file-read "$PHPENV_VERSION_FILE" ||
  { echo "phpenv: no local version configured for this directory"
    exit 1
  } >&2
fi
