#!/usr/bin/env bash
set -e
[ -n "$PHPENV_DEBUG" ] && set -x

# Provide phpenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec phpenv-versions --bare
fi

version="$1"

if [ "$version" = "--unset" ]; then
  echo "unset PHPENV_VERSION"
  unset PHPENV_VERSION
  unset version
fi

if [ -n "$version" ]; then
  # Make sure the specified version is installed.
  phpenv-prefix "$version" >/dev/null
  echo "export PHPENV_VERSION=\"${version}\""
  PHPENV_VERSION="${version}"
  unset version
fi

if [ -z "$version" ]; then
  if [ -z "$PHPENV_VERSION" ]; then
    echo "phpenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "$PHPENV_VERSION" >&2
    exit
  fi
fi


