#!/usr/bin/env bash
set -e
[ -n "$PHPENV_DEBUG" ] && set -x

PHPENV_VERSION_NAME="$(phpenv-version-name)"

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  print_version="$PHPENV_VERSION_NAME"
else
  hit_prefix="* "
  miss_prefix="  "
  print_version="$(phpenv-version)"
fi

for path in "${PHPENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    version="${path##*/}"

    if [ "$version" == "$PHPENV_VERSION_NAME" ]; then
      echo "${hit_prefix}${print_version}"
    else
      echo "${miss_prefix}${version}"
    fi
  fi
done
