#!/usr/bin/env bash
# Summary: Show the current PHP version and its origin
#
# Shows the currently selected PHP version and how it was
# selected. To obtain only the version string, use `phpenv
# version-name'.

set -e
[ -n "$PHPENV_DEBUG" ] && set -x

version_name="$(phpenv-version-name)"
version_origin="$(phpenv-version-origin)"

if [ "$version_origin" = "${PHPENV_ROOT}/version" ] && [ ! -e "$version_origin" ]; then
  echo "$version_name"
else
  echo "$version_name (set by $version_origin)"
fi
