#!/usr/bin/env bash
# Summary: Display the version of phpenv
#
# Displays the version number of this phpenv release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

set -e
[ -n "$PHPENV_DEBUG" ] && set -x

version="0.9.0-rc.1"
git_revision=""

if cd "${BASH_SOURCE%/*}" 2>/dev/null && git remote -v 2>/dev/null | grep -q phpenv; then
  git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
  git_revision="${git_revision#v}"
fi

echo "phpenv v${git_revision:-$version}"
